# Resolução de Equações Lineares usando Matriz Inversa

<b>BIBLIOTECAS

In [44]:
#Biblioteca para operações envolvendo Algebra Linear
import numpy

<b>FUNÇÃO PARA RESOLVER SISTEMAS DE EQUAÇÕES LINEARES

In [45]:
def f_sist_eq_lineares(matriz_coeficientes, matriz_resultados):
    #Encontrar a Matriz Inversa de coeficientes
    inversa_matriz_coeficientes = numpy.linalg.inv(matriz_coeficientes)
    #Calcular o Produto Escalar das matrizes
    valor_variaveis = numpy.dot(inversa_matriz_coeficientes, matriz_resultados)
    #Retornar o resultado das variáveis
    return valor_variaveis

<b>EXERCÍCIO 1:

$\begin{bmatrix}4 & 6 & 2 \\ 3 & 4 & 1 \\ 2 & 8 
& 13\end{bmatrix} \begin{bmatrix}a\\b\\c\end{bmatrix} = 
\begin{bmatrix}9\\7\\2\end{bmatrix}$

In [46]:
A = numpy.array([[4,6,2],[3,4,1],[2,8,13]], dtype="double")
R = numpy.array([[9],[7],[2]], dtype="double")
variaveis_a_b_c = f_sist_eq_lineares(A, R)
print(f"A =\n{A}")
print(f"R =\n{R}")
print(f"Variaveis =\n{variaveis_a_b_c}")

A =
[[ 4.  6.  2.]
 [ 3.  4.  1.]
 [ 2.  8. 13.]]
R =
[[9.]
 [7.]
 [2.]]
Variaveis =
[[ 3.00000000e+00]
 [-5.00000000e-01]
 [-1.05471187e-15]]


<b>EXERCÍCIO 2:

$\begin{bmatrix}1 & 1 & 1 \\ 3 & 2 & 1 \\ 2 & 1 
& 2\end{bmatrix} \begin{bmatrix}a\\b\\c\end{bmatrix} = 
\begin{bmatrix}15\\28\\23\end{bmatrix}$

In [47]:
A = numpy.array([[1,1,1],[3,2,1],[2,1,2]], dtype="double")
R = numpy.array([[15],[28],[23]], dtype="double")
variaveis_a_b_c = f_sist_eq_lineares(A, R)
print(f"A =\n{A}")
print(f"R =\n{R}")
print(f"Variaveis =\n{variaveis_a_b_c}")

A =
[[1. 1. 1.]
 [3. 2. 1.]
 [2. 1. 2.]]
R =
[[15.]
 [28.]
 [23.]]
Variaveis =
[[3.]
 [7.]
 [5.]]


<b>EXERCÍCIO 3

$\begin{bmatrix}1 & 1 & 1 \\ 3 & 2 & 1 \\ 2 & 1 
& 2\end{bmatrix}$

In [48]:
A = numpy.array([[1,1,1],[3,2,1],[2,1,2]], dtype="double")
A_inversa = numpy.linalg.inv(A)
print(f"A =\n{A}")
print(f"Inversa A =\n{A_inversa}")

A =
[[1. 1. 1.]
 [3. 2. 1.]
 [2. 1. 2.]]
Inversa A =
[[-1.5  0.5  0.5]
 [ 2.   0.  -1. ]
 [ 0.5 -0.5  0.5]]
