# Sistema de Equações Lineares

<b>DEFINIÇÃO TEÓRICA

Um sistema de equações lineares pode ser representado matematicamente da seguinte forma:

$$ AX = B $$

Isolando a variável "X":

$$ X = A^{-1}B $$

Em que:
- $ X $: Matriz de Variáveis.
- $ A $: Matriz de Coeficientes.
- $ A^{-1} $: Matriz Inversa de Coeficientes.
- $ B $: Matriz de Resultados.

Referência Bibliográfica:
- Livro: <i>Introduction to Linear Algebra - by: Gilbert Strang.</i> Disponível em: https://math.mit.edu/~gs/linearalgebra/.

<b>BIBLIOTECAS

In [1]:
#Biblioteca para operações envolvendo Algebra Linear
import numpy

<b>FUNÇÃO PARA RESOLVER SISTEMAS DE EQUAÇÕES LINEARES

In [2]:
def f_sist_eq_lineares(matriz_coeficientes, matriz_resultados):
    #Encontrar a Matriz Inversa de coeficientes
    inversa_matriz_coeficientes = numpy.linalg.inv(matriz_coeficientes)
    #Calcular o Produto Escalar das matrizes
    valor_variaveis = numpy.dot(inversa_matriz_coeficientes, matriz_resultados)
    #Retornar o resultado das variáveis
    return valor_variaveis

<b>EXEMPLO

$ 3x - 2y + z = 7 $

$ x + y + z = 2 $

$ 3x - 2y - z = 3 $

In [3]:
#Matriz de coeficientes
coeficientes = numpy.array([[3,-2,1],[1,1,1],[3,-2,-1]])
coeficientes

array([[ 3, -2,  1],
       [ 1,  1,  1],
       [ 3, -2, -1]])

In [4]:
#Matriz de resultados
resultados = numpy.array([[7],[2],[3]])
resultados

array([[7],
       [2],
       [3]])

In [5]:
#Valor das variáveis
variaveis = f_sist_eq_lineares(coeficientes, resultados)
print(f"x = {variaveis[0]}\ny = {variaveis[1]}\nz = {variaveis[2]}")
variaveis

x = [1.]
y = [-1.]
z = [2.]


array([[ 1.],
       [-1.],
       [ 2.]])